from pathlib import Path

from ..actions import compile_choice


def _quote(value) -> str:
    return repr(value)


def _condition(req: dict) -> str:
    if "variable" in req:
        return f"sf_vars.get({_quote(req['variable'])}) == {_quote(req['equals'])}"
    if "has_item" in req:
        return f"{_quote(req['has_item'])} in sf_inventory"
    if "lacks_item" in req:
        return f"{_quote(req['lacks_item'])} not in sf_inventory"
    if "owned_by" in req:
        spec = req["owned_by"]
        return f"sf_owners.get({_quote(spec['item'])}) == {_quote(spec['character'])}"
    spec = req["character"]
    return f"sf_characters.get({_quote(spec['id'])}, {{}}).get({_quote(spec['attribute'])}) == {_quote(spec['equals'])}"


def _effects(effect: dict) -> list[str]:
    if "take_item" in effect:
        item = _quote(effect["take_item"])
        return [f"sf_inventory.add({item})", f"sf_owners.pop({item}, None)"]
    if "drop_item" in effect:
        return [f"sf_inventory.discard({_quote(effect['drop_item'])})"]
    if "give_item" in effect:
        spec = effect["give_item"]
        item, character = _quote(spec["item"]), _quote(spec["character"])
        return [f"sf_inventory.discard({item})", f"sf_owners[{item}] = {character}"]
    if "character" in effect:
        spec = effect["character"]
        cid, attr = _quote(spec["id"]), _quote(spec["attribute"])
        prefix = f"sf_characters.setdefault({cid}, {{}})"
        if "set" in spec:
            return [f"{prefix}[{attr}] = {_quote(spec['set'])}"]
        op = "+" if "increment" in spec else "-"
        amount = spec.get("increment", spec.get("decrement"))
        return [f"{prefix}[{attr}] = {prefix}.get({attr}, 0) {op} {_quote(amount)}"]
    name = _quote(effect["variable"])
    if "set" in effect:
        return [f"sf_vars[{name}] = {_quote(effect['set'])}"]
    op = "+" if "increment" in effect else "-"
    amount = effect.get("increment", effect.get("decrement"))
    return [f"sf_vars[{name}] = sf_vars.get({name}, 0) {op} {_quote(amount)}"]


def export_renpy(story: dict, output: str | Path) -> Path:
    out = Path(output)
    initial_chars = story.get("character_state", {})
    lines = [
        "# Generated by StoryForge. Edit the source story, not this file.",
        "",
        f"default sf_vars = {_quote(story.get('variables', {}))}",
        f"default sf_inventory = set({_quote(story.get('inventory', []))})",
        f"default sf_owners = {_quote(story.get('ownership', {}))}",
        f"default sf_characters = {_quote(initial_chars)}",
        "",
        "label start:",
        f"    jump sf_{story['start']}",
        "",
    ]
    for scene_id, scene in story["scenes"].items():
        lines.append(f"label sf_{scene_id}:")
        scene_text = str(scene.get("text", "")).replace('"', '\\"')
        if scene_text:
            lines.append(f'    "{scene_text}"')
        choices = [compile_choice(choice) for choice in scene.get("choices", [])]
        if choices:
            lines.append("    menu:")
            for choice in choices:
                prompt = str(choice["text"]).replace('"', '\\"')
                requirements = choice.get("requires", [])
                suffix = " if " + " and ".join(_condition(req) for req in requirements) if requirements else ""
                lines.append(f'        "{prompt}"{suffix}:')
                for effect in choice.get("effects", []):
                    for statement in _effects(effect):
                        lines.append(f"            $ {statement}")
                if choice.get("goto"):
                    lines.append(f'            jump sf_{choice["goto"]}')
                else:
                    ending = story["endings"][choice["ending"]]
                    ending_text = str(ending.get("text", choice["ending"])).replace('"', '\\"')
                    lines += [f'            "{ending_text}"', "            return"]
        else:
            lines.append("    return")
        lines.append("")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    return out
