from pathlib import Path


def export_renpy(story: dict, output: str | Path) -> Path:
    out = Path(output)
    lines = ["# Generated by StoryForge. Edit the source story, not this file.", "", "label start:", f"    jump sf_{story['start']}", ""]
    for scene_id, scene in story["scenes"].items():
        lines.append(f"label sf_{scene_id}:")
        scene_text = str(scene.get("text", "")).replace('"', '\\\"')
        if scene_text:
            lines.append(f'    "{scene_text}"')
        choices = scene.get("choices", [])
        if choices:
            lines.append("    menu:")
            for choice in choices:
                prompt = str(choice["text"]).replace('"', '\\\"')
                lines.append(f'        "{prompt}":')
                if choice.get("goto"):
                    lines.append(f'            jump sf_{choice["goto"]}')
                else:
                    ending = story["endings"][choice["ending"]]
                    ending_text = str(ending.get("text", choice["ending"])).replace('"', '\\\"')
                    lines += [f'            "{ending_text}"', "            return"]
        else:
            lines.append("    return")
        lines.append("")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    return out
